[workspace]
resolver = "3"
members = ["crates/quench-check", "crates/quench-cli", "crates/quench-conf", "crates/quench-diag", "crates/quench-lex", "crates/quench-lower", "crates/quench-gen", "crates/quench-interp", "crates/quench-num", "crates/quench-parse", "crates/quench-qir", "crates/quench-dev"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Tankun Sriket"]
repository = "https://github.com/Artificial-IntelligenceAI/Quench-lang"

[profile.release]
opt-level = 3
debug = true
