[package]
name = "quench-interp"
description = "Running QIR directly, as the engine that does the least."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
quench-qir = { path = "../quench-qir" }

[dev-dependencies]
quench-dev = { path = "../quench-dev" }
